### ISSUE TITLE
Rewrite sample corr using torch like RAFT

### ISSUE THREAD

**Issue by HardysJin** [princeton-vl/DROID-SLAM#23]
Hi, thanks for the wonderful work. 

I got some questions
- why use `correlation_kernels.cu` for corr sampling? Is it faster? 
- what `corr_index_forward_kernel` function in `correlation_kernels.cu` is doing? Sorry I am a little confused.
- Is that possible to rewrite the sample corr using torch (or put it in a network format) like what RAFT did?

Thanks

**Comment by zachteed** [comment]
Hi, yes the corr sampling is exactly the same as RAFT. I implemented it as a cuda kernel to improve speed and decrease memory usage. The grid sampling operation in pytorch was a fairly large bottleneck in raft.

**Comment by HardysJin** [comment]
Thanks, got it work
