### ISSUE TITLE
Constant used to resize images in image_stream?

### ISSUE THREAD

**Issue by AI-Hunter** [princeton-vl/DROID-SLAM#27]
in demo.py, there two lines, where you use 384 and 512:
```
 h1 = int(h0 * np.sqrt((384 * 512) / (h0 * w0)))
 w1 = int(w0 * np.sqrt((384 * 512) / (h0 * w0)))
```
is it fixed values? what will be for higher resolution images?
I mean how can I choose those values to resize the images?

Thanks in advanced

**Comment by pranav-asthana** [comment]
Hi, were you able to figure this out? I have higher res images but the point cloud resolution (number of points) is limited due to this
