### ISSUE TITLE
Execution after Reconstruction path files

### ISSUE THREAD

**Issue by ChinmayBH** [princeton-vl/DROID-SLAM#56]
Hello! Thank you so much for this open source repository. Whole repo is working but I am not understanding how to use files that been generated and saved at reconstruction path. Those are 5 numpy files. Can any one guide how to use those files to create final output? that would be really useful ! Thanks again!

**Comment by MrCorsair3** [comment]
Hello, do you found solution ?

**Comment by senhuangpku** [comment]
Hello! I have the same problem, do you find the solution?

**Comment by ChinmayBH** [comment]
yes. We don't want to use those files manually anywhere. Just a suggestion that create a requirment.txt first and then install that before proceeding to the actual execution of code. that will help you to smooth execution.

**Comment by ChinmayBH** [comment]
I am closing this issue because the above mentioned method helped me to resolve issue.

**Comment by SidneyRey** [comment]
I have the same question, anyone can visualize these npy files?

**Comment by ERGOWHO** [comment]
> I have the same question, anyone can visualize these npy files?

Hi have you solved the .npy problem yet? Thanks in advance
