### ISSUE TITLE
Maybe typo in the cuda code of pose retraction

### ISSUE THREAD

**Issue by Willyzw** [princeton-vl/DROID-SLAM#7]
Thanks for releasing this excellent work!
One small thing drew my attention and unsure if this is on purpose, which is the `xi[45]` at this line.
https://github.com/princeton-vl/DROID-SLAM/blob/9843482ec70a84d28defe3def4ed84b3a77ce914/src/droid_kernels.cu#L154

**Comment by zachteed** [comment]
Thank you for pointing this out. This is indeed a bug and could cause an illegal memory access, but seems to have negligible impact on the accuracy of our system. And it only affects inference, not training or evaluation.

Anyways I am going to correct this issue. Our results may improve slightly after fixing the bug, and we are running some tests to check.

**Comment by Willyzw** [comment]
Great!
Since you have correct the index in the last commit, I am closing this issue.
