### ISSUE TITLE
How read .npy files from the reconstructions directory

### ISSUE THREAD

**Issue by MrCorsair3** [princeton-vl/DROID-SLAM#73]
Hello,
congratulations on a great project. I have a question about the situation where the --reconstruction_path flag is set, how to properly display the contents of .npy files?

**Comment by felipesce** [comment]
`import numpy as np
arr = np.load("path/to/file")
print(arr)`

**Comment by MrCorsair3** [comment]
I meant how to open it more visually

**Comment by pytholic** [comment]
@zapmxl This might be helpful:
https://github.com/pytholic/ml_cv_scripts_guides/tree/8e56fcdc433433fcd4d8b885b8c831d16541fdfd/droid_slam
